[package]
name = "bpf-postproc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bpf-postproc"
path = "src/main.rs"

[features]
default = ["llvm-22"]
llvm-22 = ["dep:llvm-sys-22"]

[dependencies]
gimli = "0.32"
thiserror = "2"
llvm-sys-22 = { package = "llvm-sys", features = [
    "disable-alltargets-init",
], version = "221.0.1", optional = true }
